# Generated by Django 4.2.7 on 2023-11-20 03:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('piso', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('habilitado', models.BooleanField(default=False)),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'Alta'), (1, 'Baja')])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioPorTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='hotel.hotel')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='core.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('coeficiente_descuento', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descripcion', models.TextField(blank=True)),
                ('habitaciones', models.ManyToManyField(related_name='paquetes', to='hotel.habitacion')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='tipos_habitacion',
            field=models.ManyToManyField(related_name='hoteles', through='hotel.PrecioPorTipo', to='core.tipohabitacion'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipohabitacion'),
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_habitaciones', models.IntegerField()),
                ('porcentaje', models.DecimalField(decimal_places=3, max_digits=5)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='hotel.hotel')),
            ],
        ),
    ]
