# Generated by Django 4.2.7 on 2023-11-26 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hotel', '0002_alter_precioportipo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='core.tipohabitacion'),
        ),
    ]
